// 20-shirt catalog for the Playwright store builder. Pure data.
export const COLLECTIONS = [
  "Best Sellers",
  "New Arrivals",
  "Graphic Tees",
  "Essentials",
  "Oversized",
  "Long Sleeve",
];

const SIZES = ["S", "M", "L", "XL", "XXL"];

// helper to keep entries short
const P = (o) => ({
  sizes: SIZES,
  qty: 40,
  vendor: "Davnoot Apparel",
  status: "active",
  ...o,
});

export const PRODUCTS = [
  P({ title: "Classic Cotton Crew Tee", handle: "classic-cotton-crew-tee", price: 24.0, compareAt: 30.0,
    type: "T-Shirts", tags: ["cotton", "everyday", "unisex"], collections: ["Best Sellers", "Essentials"],
    attrs: [["Material", "100% Combed Cotton"], ["Fit", "Regular"], ["Weight", "180 GSM"]],
    desc: "A wardrobe staple in soft 100% combed cotton with a clean crew neckline and a regular fit that holds its shape wash after wash.",
    metaTitle: "Classic Cotton Crew Tee — Soft 100% Cotton T-Shirt",
    metaDesc: "Shop our Classic Cotton Crew Tee in soft 100% combed cotton. Regular fit, durable, everyday comfort. Sizes S–XXL." }),
  P({ title: "Vintage Washed Pocket Tee", handle: "vintage-washed-pocket-tee", price: 28.0, compareAt: 34.0,
    type: "T-Shirts", tags: ["vintage", "garment-dyed", "pocket"], collections: ["New Arrivals", "Essentials"],
    attrs: [["Material", "Ring-Spun Cotton"], ["Fit", "Relaxed"], ["Feature", "Chest Pocket"]],
    desc: "Garment-dyed for a lived-in look from day one. A relaxed body, reinforced chest pocket, and that perfectly faded vintage hand-feel.",
    metaTitle: "Vintage Washed Pocket Tee — Garment-Dyed Relaxed Fit",
    metaDesc: "Garment-dyed Vintage Washed Pocket Tee with a relaxed fit and chest pocket. Soft, faded, everyday cool. Sizes S–XXL." }),
  P({ title: "Heavyweight Oversized Tee", handle: "heavyweight-oversized-tee", price: 32.0,
    type: "T-Shirts", tags: ["oversized", "heavyweight", "streetwear"], collections: ["Oversized", "Best Sellers"],
    attrs: [["Material", "Heavyweight Cotton"], ["Fit", "Oversized"], ["Weight", "240 GSM"]],
    desc: "Boxy, dropped-shoulder silhouette in a structured 240 GSM cotton. The street-ready oversized fit that actually keeps its shape.",
    metaTitle: "Heavyweight Oversized Tee — 240 GSM Boxy Streetwear",
    metaDesc: "Heavyweight 240 GSM Oversized Tee with a boxy, dropped-shoulder fit. Premium streetwear staple. Sizes S–XXL." }),
  P({ title: "Essential V-Neck Tee", handle: "essential-v-neck-tee", price: 22.0,
    type: "T-Shirts", tags: ["v-neck", "essential", "soft"], collections: ["Essentials"],
    attrs: [["Material", "Cotton-Modal Blend"], ["Fit", "Slim"], ["Neckline", "V-Neck"]],
    desc: "A flattering slim V-neck in a silky cotton-modal blend. Lightweight, breathable, and layer-friendly.",
    metaTitle: "Essential V-Neck Tee — Soft Cotton-Modal Slim Fit",
    metaDesc: "Essential V-Neck Tee in a soft cotton-modal blend with a slim fit. Breathable and easy to layer. Sizes S–XXL." }),
  P({ title: "Long Sleeve Henley Tee", handle: "long-sleeve-henley-tee", price: 34.0, compareAt: 42.0,
    type: "Long Sleeve", tags: ["henley", "long-sleeve", "buttons"], collections: ["Long Sleeve", "New Arrivals"],
    attrs: [["Material", "Waffle-Knit Cotton"], ["Fit", "Regular"], ["Feature", "3-Button Placket"]],
    desc: "A waffle-knit henley with a three-button placket and ribbed cuffs. Warm, textured, and endlessly easy to wear.",
    metaTitle: "Long Sleeve Henley Tee — Waffle-Knit 3-Button",
    metaDesc: "Waffle-knit Long Sleeve Henley Tee with a 3-button placket and ribbed cuffs. Textured everyday warmth. Sizes S–XXL." }),
  P({ title: "Striped Breton Long Sleeve", handle: "striped-breton-long-sleeve", price: 30.0,
    type: "Long Sleeve", tags: ["striped", "breton", "nautical"], collections: ["Long Sleeve"],
    attrs: [["Material", "Cotton Jersey"], ["Fit", "Regular"], ["Pattern", "Breton Stripe"]],
    desc: "The timeless Breton stripe in a midweight cotton jersey. A French-inspired classic that goes with everything.",
    metaTitle: "Striped Breton Long Sleeve Tee — Classic Nautical Stripe",
    metaDesc: "Striped Breton Long Sleeve Tee in midweight cotton jersey. Timeless nautical style. Sizes S–XXL." }),
  P({ title: "Graphic Sunset Print Tee", handle: "graphic-sunset-print-tee", price: 29.0, compareAt: 36.0,
    type: "Graphic Tees", tags: ["graphic", "print", "sunset"], collections: ["Graphic Tees", "New Arrivals"],
    attrs: [["Material", "100% Cotton"], ["Fit", "Regular"], ["Print", "Water-Based Ink"]],
    desc: "A retro sunset graphic screen-printed with soft water-based inks that won't crack. Bold front hit, clean back.",
    metaTitle: "Graphic Sunset Print Tee — Retro Screen-Printed",
    metaDesc: "Graphic Sunset Print Tee with a retro design in soft water-based inks. Bold and fade-resistant. Sizes S–XXL." }),
  P({ title: "Minimalist Logo Tee", handle: "minimalist-logo-tee", price: 26.0,
    type: "Graphic Tees", tags: ["logo", "minimal", "graphic"], collections: ["Graphic Tees", "Essentials"],
    attrs: [["Material", "Ring-Spun Cotton"], ["Fit", "Regular"], ["Print", "Small Chest Logo"]],
    desc: "A subtle embroidered chest logo on a clean, mid-weight cotton body. Understated branding done right.",
    metaTitle: "Minimalist Logo Tee — Subtle Embroidered Chest Logo",
    metaDesc: "Minimalist Logo Tee with a subtle embroidered chest mark on soft ring-spun cotton. Sizes S–XXL." }),
  P({ title: "Tie-Dye Festival Tee", handle: "tie-dye-festival-tee", price: 31.0,
    type: "Graphic Tees", tags: ["tie-dye", "festival", "colorful"], collections: ["Graphic Tees"],
    attrs: [["Material", "100% Cotton"], ["Fit", "Relaxed"], ["Process", "Hand Tie-Dyed"]],
    desc: "Each tee is hand tie-dyed, so no two are exactly alike. Swirls of color on a relaxed, festival-ready body.",
    metaTitle: "Tie-Dye Festival Tee — Hand-Dyed One-of-a-Kind",
    metaDesc: "Hand tie-dyed Festival Tee — each one unique. Relaxed fit, vivid color. Sizes S–XXL." }),
  P({ title: "Premium Pima Crew Tee", handle: "premium-pima-crew-tee", price: 38.0, compareAt: 46.0,
    type: "T-Shirts", tags: ["pima", "premium", "luxury"], collections: ["Best Sellers", "Essentials"],
    attrs: [["Material", "100% Peruvian Pima"], ["Fit", "Tailored"], ["Weight", "200 GSM"]],
    desc: "Luxuriously soft Peruvian Pima cotton with a tailored drape and a refined crew neck. The upgrade your basics deserve.",
    metaTitle: "Premium Pima Crew Tee — Peruvian Pima Cotton",
    metaDesc: "Premium Pima Crew Tee in 100% Peruvian Pima cotton with a tailored fit. Luxuriously soft. Sizes S–XXL." }),
  P({ title: "Acid Wash Skate Tee", handle: "acid-wash-skate-tee", price: 30.0,
    type: "T-Shirts", tags: ["acid-wash", "skate", "streetwear"], collections: ["Oversized", "Graphic Tees"],
    attrs: [["Material", "Heavy Cotton"], ["Fit", "Oversized"], ["Wash", "Acid Wash"]],
    desc: "An acid-washed heavyweight body with a skate-inspired back print. Broken-in feel, built to take a beating.",
    metaTitle: "Acid Wash Skate Tee — Heavyweight Oversized Streetwear",
    metaDesc: "Acid Wash Skate Tee in heavyweight cotton with a back print and oversized fit. Sizes S–XXL." }),
  P({ title: "Organic Cotton Relaxed Tee", handle: "organic-cotton-relaxed-tee", price: 27.0,
    type: "T-Shirts", tags: ["organic", "sustainable", "relaxed"], collections: ["New Arrivals", "Essentials"],
    attrs: [["Material", "GOTS Organic Cotton"], ["Fit", "Relaxed"], ["Eco", "Low-Impact Dye"]],
    desc: "Made from GOTS-certified organic cotton with low-impact dyes. Kind to skin and the planet, with an easy relaxed cut.",
    metaTitle: "Organic Cotton Relaxed Tee — GOTS Certified Sustainable",
    metaDesc: "Organic Cotton Relaxed Tee in GOTS-certified cotton with low-impact dyes. Sustainable comfort. Sizes S–XXL." }),
  P({ title: "Performance Athletic Tee", handle: "performance-athletic-tee", price: 33.0,
    type: "T-Shirts", tags: ["performance", "athletic", "moisture-wicking"], collections: ["Best Sellers"],
    attrs: [["Material", "Poly-Cotton Tech Blend"], ["Fit", "Athletic"], ["Feature", "Moisture-Wicking"]],
    desc: "A moisture-wicking tech blend with four-way stretch and flatlock seams. Engineered for movement, styled for the street.",
    metaTitle: "Performance Athletic Tee — Moisture-Wicking Stretch",
    metaDesc: "Performance Athletic Tee with moisture-wicking fabric and four-way stretch. Built to move. Sizes S–XXL." }),
  P({ title: "Boxy Crop Tee", handle: "boxy-crop-tee", price: 25.0,
    type: "T-Shirts", tags: ["crop", "boxy", "womens"], collections: ["New Arrivals", "Oversized"],
    attrs: [["Material", "Cotton Jersey"], ["Fit", "Cropped Boxy"], ["Length", "Cropped"]],
    desc: "A cropped, boxy cut in soft cotton jersey. High-waist friendly and made to pair with everything.",
    metaTitle: "Boxy Crop Tee — Cropped Cotton Jersey",
    metaDesc: "Boxy Crop Tee in soft cotton jersey with a cropped, boxy cut. High-waist friendly. Sizes S–XXL." }),
  P({ title: "Pocket Detail Raglan Tee", handle: "pocket-detail-raglan-tee", price: 29.0,
    type: "T-Shirts", tags: ["raglan", "pocket", "colorblock"], collections: ["Essentials"],
    attrs: [["Material", "Cotton Blend"], ["Fit", "Regular"], ["Sleeve", "Raglan"]],
    desc: "Contrast raglan sleeves and a tidy chest pocket give this everyday tee a sporty, vintage-baseball edge.",
    metaTitle: "Pocket Detail Raglan Tee — Contrast Baseball Style",
    metaDesc: "Pocket Detail Raglan Tee with contrast sleeves and a chest pocket. Vintage baseball vibe. Sizes S–XXL." }),
  P({ title: "Abstract Art Graphic Tee", handle: "abstract-art-graphic-tee", price: 30.0, compareAt: 38.0,
    type: "Graphic Tees", tags: ["abstract", "art", "graphic"], collections: ["Graphic Tees", "New Arrivals"],
    attrs: [["Material", "100% Cotton"], ["Fit", "Regular"], ["Print", "Full-Color DTG"]],
    desc: "Gallery-worthy abstract artwork printed edge to edge with vivid DTG color. Wear your art on your sleeve — literally.",
    metaTitle: "Abstract Art Graphic Tee — Full-Color DTG Print",
    metaDesc: "Abstract Art Graphic Tee with vivid full-color DTG printing. Gallery-worthy and bold. Sizes S–XXL." }),
  P({ title: "Thermal Waffle Long Sleeve", handle: "thermal-waffle-long-sleeve", price: 35.0,
    type: "Long Sleeve", tags: ["thermal", "waffle", "layering"], collections: ["Long Sleeve", "Essentials"],
    attrs: [["Material", "Waffle Thermal Knit"], ["Fit", "Slim"], ["Use", "Layering"]],
    desc: "A slim thermal waffle knit that traps warmth without bulk. The perfect base layer that looks good on its own.",
    metaTitle: "Thermal Waffle Long Sleeve — Slim Layering Base",
    metaDesc: "Thermal Waffle Long Sleeve in a slim waffle knit. Warm, low-bulk layering. Sizes S–XXL." }),
  P({ title: "Heavyweight Mock Neck Tee", handle: "heavyweight-mock-neck-tee", price: 32.0,
    type: "T-Shirts", tags: ["mock-neck", "heavyweight", "modern"], collections: ["New Arrivals", "Oversized"],
    attrs: [["Material", "Heavyweight Cotton"], ["Fit", "Relaxed"], ["Neckline", "Mock Neck"]],
    desc: "A structured mock neck in dense, heavyweight cotton. A modern, elevated take on the everyday tee.",
    metaTitle: "Heavyweight Mock Neck Tee — Structured Modern Cotton",
    metaDesc: "Heavyweight Mock Neck Tee in dense cotton with a relaxed fit. Modern and elevated. Sizes S–XXL." }),
  P({ title: "Retro Collegiate Tee", handle: "retro-collegiate-tee", price: 28.0,
    type: "Graphic Tees", tags: ["collegiate", "retro", "varsity"], collections: ["Graphic Tees", "Best Sellers"],
    attrs: [["Material", "Cotton Fleece-Back"], ["Fit", "Regular"], ["Print", "Flock Lettering"]],
    desc: "Varsity-style flocked lettering on a soft fleece-back cotton. Throwback collegiate energy, modern comfort.",
    metaTitle: "Retro Collegiate Tee — Varsity Flock Lettering",
    metaDesc: "Retro Collegiate Tee with varsity flock lettering on soft cotton. Throwback style. Sizes S–XXL." }),
  P({ title: "Linen Blend Summer Tee", handle: "linen-blend-summer-tee", price: 33.0,
    type: "T-Shirts", tags: ["linen", "summer", "breathable"], collections: ["New Arrivals", "Essentials"],
    attrs: [["Material", "Cotton-Linen Blend"], ["Fit", "Relaxed"], ["Season", "Summer"]],
    desc: "A breezy cotton-linen blend with a natural slub texture. Cool, breathable, and made for warm days.",
    metaTitle: "Linen Blend Summer Tee — Breathable Cotton-Linen",
    metaDesc: "Linen Blend Summer Tee in a breathable cotton-linen mix with natural texture. Sizes S–XXL." }),
];
